import { PackageInfo, ZodObjectInfo, FunctionInfo, IpcFrameworkConfig } from "./types";
import { createRelativeImportPath, formatParameters } from "./utils";

/**
 * Generates the preload script content
 * @param zodObjectInfos - Zod object information
 * @param packages - Package information
 * @returns Generated preload script content
 */
export function generatePreloadScript(
  zodObjectInfos: ZodObjectInfo[],
  packages: PackageInfo[]
): string {
  const functionLines = generateFunctionCalls(packages, zodObjectInfos, (functions) => {
    return functions.map(func => {
      const params = formatParameters(func.parameters);
      const paramNames = func.parameters.map(p => p.name).join(', ');
      
      return `${func.name}: (${params}) => ipcRenderer.invoke("${func.name}", { ${paramNames} })`;
    });
  });
  
  return `// Auto-generated by @electron-flow/framework
// Do not edit this file manually
import { ipcRenderer } from "electron";

export default {
    ${functionLines.join(',\n    ')}
};
`;
}

/**
 * Generates the main process register script content
 * @param packages - Package information
 * @param registerPath - Path where the register script will be saved
 * @param config - Framework configuration
 * @returns Generated register script content
 */
export function generateRegisterScript(
  packages: PackageInfo[],
  registerPath: string,
  config?: IpcFrameworkConfig
): string {
  const importStatements = generateImportStatements(registerPath, packages, (functionNames, importPath) => {
    return `import { ${functionNames} } from "${importPath}";`;
  });
  
  // エラーハンドラーの設定
  const errorHandlerConfig = config?.errorHandler || {};
  const errorHandlerFunction = errorHandlerConfig.functionName || 'handleIpcError';
  const errorHandlerImport = errorHandlerConfig.importPath || '../../error-handler';
  
  const handlerStatements = packages.flatMap(pkg => {
    return pkg.functions.map(func => {
      const hasParams = func.parameters.length > 0;
      
      return `"${func.name}": (ctx: Omit<Context, "event">) => {
        return async (event: IpcMainInvokeEvent, args: any) => {
            try {
                const result = await ${func.name}({ ...ctx, event }${hasParams ? ', args' : ''});
                return success(result);
            } catch (e: any) {
                return ${errorHandlerFunction}(e);
            }
        };
    },`;
    });
  });
  
  return `// Auto-generated by @electron-flow/framework
// Do not edit this file manually
import { Context } from "../../context";
import { ipcMain, IpcMainInvokeEvent } from "electron";
import { success } from "@electron-flow/shared";
import { ${errorHandlerFunction} } from "${errorHandlerImport}";

${importStatements.join('\n')}

export const autoGenerateHandlers = {
    ${handlerStatements.join('\n    ')}
};

export function registerAutoGenerateAPI(ctx: Omit<Context, "event">) {
    Object.entries(autoGenerateHandlers).forEach(([key, value]) => {
        ipcMain.handle(key, value(ctx));
    });
}

export function removeAutoGenerateAPI() {
    Object.keys(autoGenerateHandlers).forEach(key => {
        ipcMain.removeHandler(key);
    });
}
`;
}

/**
 * Generates the renderer types content
 * @param packages - Package information
 * @param zodObjectInfos - Zod object information
 * @param rendererTypesPath - Path where the renderer types will be saved
 * @returns Generated renderer types content
 */
export function generateRendererTypes(
  packages: PackageInfo[],
  zodObjectInfos: ZodObjectInfo[],
  rendererTypesPath: string
): string {
  const importStatements = generateImportStatements(rendererTypesPath, packages, (functionNames, importPath) => {
    return `import type { ${functionNames} } from "${importPath}";`;
  });
  
  const functionLines = generateFunctionCalls(packages, zodObjectInfos, (functions) => {
    return functions.map(func => {
      const params = formatParameters(func.parameters);
      return `${func.name}: (${params}) => Promise<Result<ReturnTypeUnwrapped<typeof ${func.name}>>>`;
    });
  });
  
  return `// Auto-generated by @electron-flow/framework
// Do not edit this file manually
${importStatements.join('\n')}
import { Result } from "@electron-flow/shared";

// Promise unwrapping utility type
type UnwrapPromise<T> = T extends Promise<infer U> ? U : T;

// Function return type unwrapping utility
type ReturnTypeUnwrapped<T> = T extends (...args: any[]) => infer R
    ? UnwrapPromise<R>
    : never;

export interface AutogenerateAPI {
    ${functionLines.join(';\n    ')}
}
`;
}

/**
 * Generates import statements for code generation
 */
function generateImportStatements(
  outputPath: string,
  packages: PackageInfo[],
  formatter: (functionNames: string, importPath: string) => string
): string[] {
  return packages
    .filter(pkg => pkg.functions.length > 0)
    .map(pkg => {
      const functionNames = pkg.functions.map(func => func.name).join(', ');
      const importPath = createRelativeImportPath(outputPath, pkg.path);
      return formatter(functionNames, importPath);
    });
}

/**
 * Generates function calls with proper type resolution
 */
function generateFunctionCalls(
  packages: PackageInfo[],
  zodObjectInfos: ZodObjectInfo[],
  formatter: (functions: FunctionInfo[]) => string[]
): string[] {
  const functions = packages.flatMap(pkg => {
    return pkg.functions.map(func => {
      // Resolve parameters through zod type relations
      const resolvedParameters = func.parameters.reduce((acc, param) => {
        const typeRelation = pkg.typeRelations.find(rel => rel.dist === param.type);
        
        if (typeRelation) {
          const zodObjectInfo = zodObjectInfos.find(zod => zod.name === typeRelation.src);
          
          if (zodObjectInfo) {
            // Expand zod object fields
            return [...acc, ...zodObjectInfo.fields];
          }
        }
        
        // Keep original parameter if no zod relation found
        return [...acc, param];
      }, [] as { name: string; type: string }[]);
      
      return {
        name: func.name,
        parameters: resolvedParameters
      };
    });
  });
  
  return formatter(functions);
}
